# Generated by Django 5.2.4 on 2025-08-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='Школа')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='Класс')),
                ('goal', models.TextField(blank=True, verbose_name='Цель занятий')),
                ('notes', models.TextField(blank=True, verbose_name='Доп. заметки')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема занятия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Сумма оплаты')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Задание')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('grade', models.CharField(blank=True, max_length=10, verbose_name='Оценка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='core.student')),
            ],
        ),
    ]
